// <auto-generated />
namespace Bll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class QS2MX1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QS2MX1));
        
        string IMigrationMetadata.Id
        {
            get { return "202106291805438_QS2MX-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
